name: CI

on:
  push:
    branches: ["main", "dev"]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          cache: "true"

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "pnpm"

      - name: Setup build cache
        uses: actions/cache@v5
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: Install dependencies
        run: pnpm install

      - name: Check commit name
        if: github.event_name == 'pull_request'
        run: pnpm commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: Format check
        run: pnpm run format:check
        if: always()

      - name: Build
        run: pnpm run build
        env:
          NEXT_PUBLIC_API_URL: http://localhost:8000
        if: always()

      - name: Lint
        run: pnpm run lint
        if: always()
